apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "mysite"
  labels:
    app: "mysite"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "mysite"
  template:
    metadata:
      labels:
        app: "mysite"
    spec:
      containers:
        - name: "mysite"
          image: "<AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/mysite:IMAGE_ID"
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
